#!/bin/sh

USER=searchtenders
GROUP=searchtenders
NAME=search-tenders
HOME=/opt/$NAME

if ! id $USER ; then
  adduser --system --home $HOME --no-create-home --shell /bin/false --group $GROUP
fi

for DIR in $HOME/var $HOME/var/log $HOME/var/run /var/log/$NAME ; do
  mkdir -p $DIR
  chown -R $USER:$GROUP $DIR
done

if [ -d /etc/elasticsearch ] ; then
  test -e /etc/elasticsearch/stopwords || mkdir /etc/elasticsearch/stopwords
  cp -n $HOME/share/stopwords/*.txt /etc/elasticsearch/stopwords
fi

if [ -x /usr/sbin/update-rc.d ] ; then
  /usr/sbin/update-rc.d $NAME defaults
  /usr/sbin/update-rc.d $NAME enable
fi

if [ -x /bin/systemctl ] ; then
  /bin/systemctl daemon-reload
fi
