#!/bin/sh

if ! id searchtenders ; then
  adduser --system --home /opt/search.tenders --no-create-home --shell /bin/false --group searchtenders
fi

chown searchtenders:searchtenders /opt/search.tenders/var
chown searchtenders:searchtenders /var/log/search.tenders

if [ -x /usr/sbin/update-rc.d ] ; then
  /usr/sbin/update-rc.d search-tenders defaults
  /usr/sbin/update-rc.d search-tenders enable
fi

if [ -x /bin/systemctl ] ; then
  /bin/systemctl daemon-reload
fi
