#!/bin/sh

[ -x /etc/init.d/search-tenders ] || exit 0

/etc/init.d/search-tenders stop

[ -x /usr/sbin/update-rc.d ] || exit 0

/usr/sbin/update-rc.d -f search-tenders remove

[ -d /opt/search.tenders ] || exit 0

find /opt/search.tenders -name \*.pyc -delete
#rm -f /opt/search.tenders/var/*
