#!/bin/sh

BASEDIR=${buildout:directory}
CONFDIR=${buildout:directory}/etc
LOGSDIR=${buildout:directory}/var/log
CONTROL=$BASEDIR/bin/circusctl

cd $BASEDIR || exit 1

clean_indexes()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/clean_indexes $INI >>$LOGSDIR/clean_indexes.log 2>&1
  done
}

do_restart_indexer()
{
  echo "["`date`"] Restart search-tenders"
  $CONTROL stop
  while [ `$CONTROL status | grep -c -v stopped` -ne 0 ] ; do
    sleep 1
  done
  sleep 2
  $CONTROL start
}

restart_indexer()
{
  do_restart_indexer >>$LOGSDIR/restart.log 2>&1
}

ocds_ftp_sync()
{
  $BASEDIR/bin/ocds_ftp_sync $CONFDIR/ftpsync.ini >>$LOGSDIR/ftpsync.log 2>&1
}

update_orgs()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/update_orgs $INI >>$LOGSDIR/update_orgs.log 2>&1
  done
}

test_search()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/test_search $INI >>$LOGSDIR/test_search.log 2>&1
  done
}


case $1 in
clean)      clean_indexes   ;;
reload)     restart_indexer ;;
ftpsync)    ocds_ftp_sync   ;;
update)     update_orgs     ;;
test)       test_search     ;;
*)  echo "Usage: $0 {clean|reload|ftpsync|update|test}"
	exit 1
esac

