#!/bin/sh

BASEDIR=${buildout:directory}
CONFDIR=${buildout:etc-directory}
LOGSDIR=${buildout:log-directory}
CONTROL=$BASEDIR/bin/circusctl

cd $BASEDIR || exit 1

clean_indexes()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/clean_indexes $INI >>$LOGSDIR/clean.log 2>&1
  done
}

do_restart_workers()
{
  echo "["`date`"] Restart search-tenders"
  $CONTROL stop
  while [ `$CONTROL status | grep -c -v stopped` -ne 0 ] ; do
    sleep 1
  done
  sleep 2
  $CONTROL start
}

restart_workers()
{
  do_restart_workers >>$LOGSDIR/restart.log 2>&1
}

check_and_restart()
{
  TODAY=`date +%Y-%m-%d`
  COUNT=`tail $LOGSDIR/index*.log | grep -c $TODAY`
  echo "["`date`"] Check log for $TODAY found $COUNT" >>$LOGSDIR/restart.log
  if [ $COUNT -eq 0 ] ; then
    restart_workers
  fi
}

do_reload_workers()
{
  echo "["`date`"] Reload search-tenders"
  $CONTROL restart
  sleep 5
  if [ ! -s $PIDFILE -a -S $SOCKET ] ; then
    $CONTROL dstats | awk '$2~/python/{print $1}' >$PIDFILE
  fi
}

reload_workers()
{
  do_reload_workers >>$LOGSDIR/restart.log 2>&1
}

rotate_logs()
{
  if [ -x /usr/sbin/logrotate ] ; then
    /usr/sbin/logrotate $CONFDIR/logrotate.conf >/dev/null
  fi
}

update_orgs()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/update_orgs $INI >>$LOGSDIR/update.log 2>&1
  done
}

test_search()
{
  for INI in $CONFDIR/search*.ini
  do
    $BASEDIR/bin/test_index $INI >>$LOGSDIR/test.log 2>&1
    $BASEDIR/bin/test_search $INI -i >>$LOGSDIR/test.log 2>&1
  done
}


case $1 in
clean)      clean_indexes   ;;
restart)    restart_workers ;;
reload)     reload_workers  ;;
logcheck)   check_and_restart ;;
update*)    update_orgs     ;;
rotate*)    rotate_logs     ;;
test)       test_search     ;;
*)  echo "Usage: $0 {clean|restart|reload|logcheck|ftpsync|update|rotate|test}"
	exit 1
esac

